# the test suite runs the tests (headless, server+client) for multiple Meteor releases
name: Test suite
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        meteorRelease: ['3.0-beta.0']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Setup Meteor
        uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: ${{ matrix.meteorRelease }}

      - name: Setup tests
        run: |
          meteor create --release ${{ matrix.meteorRelease }} --bare test
          cd test
          meteor npm i --save puppeteer@1.18.1 chai

      - name: Test
        working-directory: ./test
        run: |
          meteor --version
          METEOR_PACKAGE_DIRS="../" TEST_BROWSER_DRIVER=puppeteer meteor test-packages --raw-logs --once --driver-package meteortesting:mocha ../
